import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  paginaInicial: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
    width: '100%',
    height: '100%',
  },
  foto: {
    width: 300,
    height: 300,
    borderRadius: 200,
    marginBottom: 20,
  },
  nome: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 50,
    textDecorationLine: 'underline',
  },
  info: {
    color: 'aqua',
    fontWeight: 'bold',
    fontSize: 20,
    textDecorationLine: 'underline',
  },
  container: {
    flex: 1,
    backgroundColor: '#fff',
    paddingTop: 24,
  },
  header: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    padding: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  titulo: {
    fontSize: 20,
    fontWeight: 'bold',
  },
  menuIcon: {
    padding: 10,
  },
  menu: {
    backgroundColor: '#f9f9f9',
    padding: 10,
  },
  menuItem: {
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: '#ccc',
  },
  menuItemText: {
    fontSize: 16,
  },
  content: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  pagina: {
    flex: 1,
    justifyContent: 'center',
    alignItems: 'center',
  },
  textoPagina1: {
    fontSize: 50,
    color: 'aqua',
    fontWeight: 'bold',
    marginBottom: 30,
    textDecorationLine: 'underline',
  },
  sobre: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'justify',
    justifyContent: 'center',
    padding: 10,
    fontSize: 17,
  },
  textoPagina2: {
    fontSize: 35,
    color: 'aqua',
    fontWeight: 'bold',
    marginBottom: 10,
    marginTop: 40,
    textDecorationLine: 'underline',
  },
  academico: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
    fontSize: 13,
  },
  textoPagina3: {
    fontSize: 35,
    color: 'aqua',
    fontWeight: 'bold',
    marginBottom: 60,
    textDecorationLine: 'underline',
  },
  skills: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    marginBottom: 10,
    fontSize: 15,
    textAlign: 'justify',
    justifyContent: 'center',
  },
  textoPagina4: {
    fontSize: 45,
    color: 'aqua',
    fontWeight: 'bold',
    marginBottom: 20,
    textDecorationLine: 'underline',
  },
  projects: {
    color: 'white',
    fontWeight: 'bold',
    textAlign: 'center',
    fontSize: 25,
    textDecorationLine: 'underline',
    marginTop: 10,
  },
  github: {
    width: 250,
    height: 250,
    borderRadius: 200,
    marginBottom: 20,
  },
  textoPagina5: {
    fontSize: 45,
    color: 'aqua',
    fontWeight: 'bold',
    marginBottom: 10,
    textDecorationLine: 'underline',
  },
  contactsContainer: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    justifyContent: 'center',
    alignItems: 'center',
  },
  contactIcon: {
    width: 80,
    height: 80,
    borderRadius: 100,
    margin: 15,
    marginBottom: 20,
  },
  frase: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 20,
    textDecorationLine: 'underline',
    textAlign: 'center',
    marginTop: 20,
  },
  autor: {
    color: 'white',
    fontWeight: 'bold',
    fontSize: 20,
    textDecorationLine: 'underline',
    marginTop: 25,
  },
});

export default styles;